export interface Students{
    // Generated by https://quicktype.io


     id:    number;
    name:     string;
    email:    string;
    mobile:   number;
    gender:   string;
    dob:      string;
    subjects: Subject[];
}

export interface Subject {
    subject: string;
    mark:    number;
    grade:   string;
}

